name: DN


on: [push, workflow_dispatch]


schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'



 jobs:

   test_schedule:
      
       

  build:


    runs-on: windows-latest
    
      
      


    steps:
    
    - name: Not on Monday or Wednesday
      if: github.event.schedule != '30 5 * * 1,3'
      run: echo "This step will be skipped on  Monday and Wednesday"
    - name: Every time
      run: echo "This step will always run"

    - name: Download

      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract

      run: Expand-Archive ngrok.zip

    - name: Auth

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Process

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "WIN-808JQ836AMQ" -Value 80

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Admin@123" -Force)

    - name: Create VM.

      run: .\ngrok\ngrok.exe tcp --region us 3389
